export const SET_ITEM = 'SET_ITEM';
export const SET_AUTH_ID = 'SET_AUTH_ID';

export const ADD_POST_ID_TO_THREAD = 'ADD_POST_ID_TO_THREAD';
export const ADD_THREAD_TO_FORUM = 'ADD_THREAD_TO_FORUM';
export const ADD_THREAD_TO_USER = 'ADD_THREAD_TO_USER';
export const ADD_CONTRIBUTORS_TO_THREAD = 'ADD_CONTRIBUTORS_TO_THREAD';
export const UNSUBSCRIBE = 'UNSUBSCRIBE';
export const SET_AUTH_USER_UNSUBSCRIBE = 'SET_AUTH_USER_UNSUBSCRIBE';
export const CLEAR_UNSUBSCRIBES = 'CLEAR_UNSUBSCRIBES';
export const SET_AUTH_OBSERVER_UNSUBSCRIBE = 'SET_AUTH_OBSERVER_UNSUBSCRIBE';